### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by jollysean** [moses-palmer/pynput#10]
Hi,

Is there a way to do Try Catch Traceback in pynput. I have tried all sort of excepiont handling in on_click block or with listener: , but no avail.

Any hints please?

**Comment by moses-palmer** [comment]
Can you provide a minimal sample of where you want to catch exceptions?

It should generally be possible as long as it is your code; the operation
system callbacks are performed in different threads though, so anything
outside of your code will be difficult to handle; uncaught exceptions are
bugs in pynput, which will have to be addressed.

**Comment by jollysean** [comment]
Here is a sample code, on_xyz are usual
```
from __future__ import absolute_import, division, print_function, unicode_literals
from pynput.mouse import Listener as mlisnr
from pynput.keyboard import Key,  Listener as klisnr
def main():
    # Collect events until released
    with klisnr( on_press=on_press, on_release=on_release) as kl,mlisnr(  on_click=on_click, on_scroll=on_scroll) as ml  :
        while True :
            try:
                #kl.join()
                ml.join()
                time.sleep(5)
                kl.stop
                ml.stop
                print("Stopped")
            except Exception as e:
                print("Some error in Mouse/Keyboard Listeners"+e)
                traceback.print_exc(file=sys.stdout)
                kl.stop
                ml.stop

if __name__ == "__main__":
    main()
```

**Comment by jollysean** [comment]
Also in on_clicked:

```
`def on_click(x, y, button, pressed):


    driver = webdriver.Chrome("C:\work\chromedriver_win32\chromedriver.exe")
    try:

        print("URL = "+str(driver.current_url))
        #driver.get('http://codepad.org')
    except Exception as e:
        traceback.print_exc(file=sys.stdout)
`
```

**Comment by moses-palmer** [comment]
What is the expected behaviour, and what does happen?

In the on_click handler, any exception except for what might be raised by
webdriver.Chrome(...) will be logged, but errors raised by that particular
call will disappear into the void. A future enhancement might be to pass
those errors to the main thread.

The code in your main with block will generally just catch exceptions
raised in your own code, as the bookkeeping is rather minimal.


On 30 Dec 2016 21:57, "Prabhat" <notifications@github.com> wrote:

Also in on_clicked:

`def on_click(x, y, button, pressed):


    driver = webdriver.Chrome("C:\work\chromedriver_win32\chromedriver.exe")
    try:

        print("URL = "+str(driver.current_url))
        #driver.get('http://codepad.org')
    except Exception as e:
        traceback.print_exc(file=sys.stdout)
`

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/moses-palmer/pynput/issues/10#issuecomment-269821003>,
or mute the thread

**Comment by jollysean** [comment]
Thanks. Look forward to future. Anyway I can contribute?
Is there a feature list for next version planned?

**Comment by moses-palmer** [comment]
There is not really a list of features available---I guess a github wiki page would be perfect for that. The features that I have plans to implement include:

*  **Support for simulating multi touch tablets.** This would be a new type of input device along *keyboard* and *mouse*. I have not yet looked in to whether this is actually supported on all platforms.
*  **Migration plan for Linux.** Since *X* will soon be replaced in some distributions, backends to support *Wayland* and *Mir* are required. This may unfortunately not be possible, since at least *Wayland* does not support any of the functionality required by *pynput* by default.
*  **Support for all [lock keys](https://en.wikipedia.org/wiki/Language_input_keys).** The first step would be make the *caps lock* implementation less hardcoded to make is easier to add lock keys. This first step would also help with implementing support for the numeric keypad and *num lock*.
*  **Adding a `CONTRIBUTING.md` file.**

**Comment by jollysean** [comment]
Thanks. Is there a plan to add unicode conversion of keys. Something like this here: https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731%28v=vs.85%29.aspx

**Comment by moses-palmer** [comment]
Unicode characters are supported as input to `pynput.keyboard.Controller` and are possible to retrieve in the callbacks registered with `pynput.keyboard.Listener`; I'm afraid that I don't really understand what you mean by *unicode conversion of keys*. The constants listed in the link you provided are defined [here](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/_util/win32_vks.py).

By the way, I have changed the listener code to not discard exceptions raised by callbacks; the are now reraised when the listener thread is joined. As this breaks the old API, the version will be bumped to *1.2* with the next release.
