### ISSUE TITLE
Detection of key combination

### ISSUE THREAD

**Issue by masoudr** [moses-palmer/pynput#103]
Hi,
I'm using `v1.4`, my problem happened only for this version.
I'm trying to detect key combinations like `ctrl+C`, `ctrl+A`, etc. But I only get `ctrl` or `c` keys. Here is my sample code:

```
from pynput import keyboard

def on_press(key):
    if key == keyboard.Key.esc:
        listener.stop()
    else:
        print(ord(getattr(key, 'char', '0')))

controller = keyboard.Controller()
with keyboard.Listener(
        on_press=on_press) as listener:
    listener.join()
```

**Comment by TheoRet** [comment]
As far as I know, pynput does not provide a mechanism to combine key events to combinations.

But if you only want two-key combinations, you can easily write your own mechanism using a global variable that saves the last pressed key.

**Comment by TheoRet** [comment]
As far as I know, pynput does not provide a mechanism to combine key events to combinations. 

But if you only want two-key combinations, you can easily write your own mechanism using a global variable that saves the last pressed key.



> I'm using v1.4, my problem happened only for this version.

What do you mean by this? Did it work in an earlier version?

**Comment by masoudr** [comment]
@TheoRet, Yes, the problem happens for version 1.4. Suppose the above example, on v1.3.10 I get the exact code for pressing two keys at the same time for example for `control + c` I get 3 but on v1.4 I only get `control` number or `c` number which is different.

**Comment by moses-palmer** [comment]
The only relevant change between *1.3.10* and *1,4* for *Windows* that I can see is

```diff
diff --git a/lib/pynput/_util/win32.py b/lib/pynput/_util/win32.py
index c0f27c6..5440f0e 100644
@@ -633,22 +636,6 @@ class KeyTranslator(object):
 
     @contextlib.contextmanager
     def _thread_input(self):
-        """Temporarily attaches the input handling of this thread to that of
-        the currently active window.
-
-        The context manager returns the ID of the thread to which the input
-        handling is attached. This is the ID of the current thread if attaching
-        failed.
+        """Yields the current thread ID.
         """
-        remote_thread = self._GetWindowThreadProcessId(
-            self._GetForegroundWindow(),
-            None)
-        local_thread = GetCurrentThreadId()
-
-        if self._AttachThreadInput(local_thread, remote_thread, True):
-            try:
-                yield remote_thread
-            finally:
-                self._AttachThreadInput(local_thread, remote_thread, False)
-        else:
-            yield local_thread
+        yield GetCurrentThreadId()
```

This was introduced in commit [`63aab1a`](https://github.com/moses-palmer/pynput/commit/63aab1acf3b66b37f4ebac72be958a505e382a06). Does the error persist if you revert this commit?

I assume you run your application from a command window. `cmd.exe` appears to modify keyboard events when it is foreground window. What happens if you switch to a different application, both with the commit present and without?

**Comment by masoudr** [comment]
@moses-palmer It doesn't matter if I focus on `cmd` or other applications, I always get the wrong values for `v1.4` and works fine for `v1.3.10`. I tried to switch to the commit you mentioned but it behaves like `v1.4`.

**Comment by gabycperezdias** [comment]
@masoudr Same issue on Mac (High Sierra) and Ubuntu (18.04)

**Comment by moses-palmer** [comment]
I took the liberty to test with the above mentioned commit reverted, and I can verify that the output of your script does change.

The previous output is unfortunately incorrect, and the commit addresses that: `cmd.exe` interferes with the keyboard handling and causes incorrect listener events---for example missing identifiers and incorrect key code for <kbd>Ctrl+C</kbd>.

The correct way to detect the key combinations you want is to take the modifier into account; doing otherwise will cause your program to malfunction when not running in a `cmd.exe` window.

**Comment by gabycperezdias** [comment]
On Mac (High Sierra) I get different number for `c` (or any other letter when combined with cmd) I also get these in the `1.3.10`.

On Ubuntu 18.04 everything works as expected in both versions

On Windows, on console, it works as expected, but when running in a program I can't simulate because I am not receiving any signals at all...
