### ISSUE TITLE
Characters with special accent not well written

### ISSUE THREAD

**Issue by schizophrene** [moses-palmer/pynput#118]
Hello !

I saw that characters with special accent (like `^`, `¨`, ...) are not well written when a Pynput Listener instance is running : 

    from pynput import keyboard
    
    def on_press(key):
        try:
            print('alphanumeric key {0} pressed'.format(
                key.char))
        except AttributeError:
            print('special key {0} pressed'.format(
                key))
    
    def on_release(key):
        print('{0} released'.format(
            key))
        if key == keyboard.Key.esc:
            # Stop listener
            return False
    
    # Collect events until released
    with keyboard.Listener(
            on_press=on_press,
            on_release=on_release) as listener:
        listener.join()

Examples : 

    special key Key.shift_r pressed
    alphanumeric key ^ pressed
    Key.shift_r released
    ['^'] released
    alphanumeric key ö pressed
    'ö' released

=> `ô` is written

    alphanumeric key ^ pressed
    ['^'] released
    alphanumeric key ô pressed
    'ô' released

=> sometimes, `o` is written. Othertimes, `ô` is written

**Comment by schizophrene** [comment]
Oh, yeah, I didn't mentioned that : yes, I am on Windows.

**Comment by juancroldan** [comment]
I'm also having the same problem on Windows. Some times I can write accents properly but eventually keystroke modifiers such as `\`` are applied to the second pressed key. Thus, If I press `\`, `A`, `A`, it writes `aá` instead of `áa`.

Is there any solution to this problem? Can I use `win32_event_filter` to solve it?

**Comment by juancroldan** [comment]
If someone else has found this thread, let me save you a few hours of research on keyboard capturing with Python on Windows:

* **Pynput:** Scrambles accent keystrokes in Windows. See [Issue #118](https://github.com/moses-palmer/pynput/issues/118).
* **Keyboard:** Is not working in Windows due to a ctypes Win32 error. See [Issue #157](https://github.com/boppreh/keyboard/issues/157). Otherwise `keyboard.read_event` (polling) or `keyboard.hook` (notification) would do the thing.
* **PyHook:** It also [scrambles keystrokes](https://sourceforge.net/p/pyhook/bugs/2/). The [docs](https://sourceforge.net/p/pyhook/wiki/PyHook_Tutorial/) are a bit obscure, and the [library is not in pip](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyhook).
* **PyGame:** It is required [to create a Window](https://stackoverflow.com/questions/36876829/pygame-key-listener-for-python-3) to capture keyboard events.
* **Msvcrt:** Only works in console apps, similar to C `getch` function.
* **Curses:** Only able to capture key events [in the console](https://stackoverflow.com/questions/16740385/python-curses-redirection-is-not-supported/33958141#33958141).
* **Termios:** Not available in Windows.

These are the alternatives I haven't explored yet:

* **PyWin32:** This could be a good choice, since it is being used on many other parts of the interface.
* **GTK, TKinter:** Maybe that's an overkill, maybe they require to have a window opened as with PyGame.

And of course, [fixing the error in this library by yourself](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_win32.py). It is required to know a bit about pywin32 library. Usually, after looking at other implementations of the things I try to achieve with it, I end up getting things done, but it requires putting some effort.

**Comment by moses-palmer** [comment]
@juancroldan , thank you for the great suggestions!

I am rather certain that the culprit is [KeyTranslator](https://github.com/moses-palmer/pynput/blob/a269c0eda31745d4e8f3d14e53679ce5fbfc7210/lib/pynput/_util/win32.py#L410), and more spcifically its use of [ToUnicodeEx](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-tounicodeex); as noted in the remarks section, it modifies a kernel-mode keyboard buffer. *pynput* attempts to work around the fact that it modifies system global state, but that is not really possible.

The tricky part is translating keyboard events to characters. The listener receives a [KEYBDINPUT](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-tagkeybdinput) struct, which contains only a virtual key code and a scan code, and my spelunking through the *win32* APIs have revealed only `ToUnicodeEx` as a means to convert them to actual characters.

I guess one way to solve this would be to maintain a representation of the entire keyboard in memory, just like the kernel apparently does, and generate characters based on the currently pressed keys. That is quite a lot of work though.

**Comment by segalion** [comment]
Hello. I have experienced same problem (listener keyboard on windows and spanish keyboard). 

If it can help you, I have discovered that mainly fails deadkeys:
1: ´ (spanish accent)
2: ¨ (shift + ´)
3: ` (inverted accent)
4: ^ (shift + `)

áéíóú (generated by keypress first deadkey ´ and next the vocal) output first the vocal and next deadkey ´ similar as if you pressed first the vocal and next the deadkey (that is written only when the next third key pressed)

The same behaviour for: äëïöü àèìòù âêîôû 

The other function of this deadkeys (with Alt-Gr+deadkey)
5: { ( alt-gr + deadkey ´ ) 
6: [ ( alt-gr + deadkey ` )
fails too (putting an additional ´ over the next two keys)
i.e if you type:
{example 
it output:
{e´xample
(put an undesired ´ when you type the 'x', just before the 'x')

Please. Dou you think you can solve this. Because this problem make keyboard listener aboslutely unusable in windows.

Thanks in advance.

**Comment by segalion** [comment]
Hello.
I have tested again, and I cant explain why now the behaviour is different:
Now, if i type:
1: ´ (spanish accent) and 3: ` (inverted accent)
works fine in all cases!!!

But 2: ¨ (shift + ´) and 4: ^ (shift + `) works like 1 and 3 (as if shift key doesnt pressed)

And again, the '{' character (reached in spanish keyboard with [ Alt-Gr + ´ ])  or '[' character (with [ Alt-Gr + ` ]) make activate the dead key, so next character would be erroneously "accented". 
If you type:

{a {b [e [f

it output:

{á {´b [è [`f


Please could you help here? Its important correct this because if you want to have a permanet global keys bindings in windows, the keyboard for the user become faulty. 

I cant understand why have a hook to keyboard to an application break the keyboard for all other applications. The hook is supposed to be transparent to the system keyboard (read-only).

Thanks in advance.

**Comment by SpecialCharacter** [comment]
It's sad that this is still not solved...

I tried various methods, but the problem is always that pynput on Windows simply ignores the first deadkey press and waits for a second key press. Therefore ´aa = á.

Interesting thing is that for AutoHotkey on Windows, this is not a problem. So in principle it should work... Unfotunately I have no clue how to program this.

**Comment by sxz0** [comment]
I have the same problem!

**Comment by sxz0** [comment]
Finally I solved the problem using Keyboard library instead. To solve the problem with this library mentioned by @juancroldan, I had to manually download the master branch in https://github.com/boppreh/keyboard and use it directly in my project, instead of using the library version downloaded using _pip install keyboard_

**Comment by segalion** [comment]
Thanks a lot. I will try...

Its a pitty pynput continues breaked in windows. I can see that keyboard seems to miss some functionalities (no mouse, linux root?, OSX experimental?), so it cannot be a full replacement.

I was writting a wrapper around pynput for mouse and keyboard, but seems that if this bug is not solved soon I have to migrate to 'keyboard' library only for 'keyboard@windows', and left pynput library for 'keyboard@linux', 'keyboard@osx' and 'mouse@all' (with means a lot of effort).

**Comment by segalion** [comment]
Any new about this problem in windows platform?

Seems that there are a lot of closed issues, but this issue remains unresolved since 2018.

I think is one of the most important issue because make pynput (keyboard hook) almost completely unusable in windows enviroment, and seems there are no solution...

Thanks again

**Comment by akiratakasaki** [comment]
Same in linux and windows, there are a few workarounds, but they are all non pythonic way's to solve this. As a newbie i was thinking i was decoding/encoding wrongly. With the help of a senior programmer we concluded that its actually pynput that is not coded in a way to serve the special chars, that's because on a us keyboard people do not have the @ char on the é key etc...., in America they seldom use these char's. With some help of a senior programmer we concluded that pynput is only "American user-friendly" , witch is a pitty. Lots of people in the world that use é, è, à ,§, ù, µ, ë, . the good news is , that my knowledge of unicode and decoding/encoding has improved a lot.
I sure wish that this problem gets solved. I am following a python course on udemy, and even the instructor could not help me out. I know now that this problem is not in due to my lack of understanding and can carry on  with the python course. i've settled for an non pythonic workaround for this particular exercise with pynput.
Still i hope pynput get's fixed.

**Comment by akiratakasaki** [comment]
Sure i agree, i was just pointing out that the problem does not only exists in windows but also in linux! i was searching day in day out for a solution for about 3 weeks, only because i could not get the @ sign recorded, and that's because the @ sign is the combination of Altgr + é. Anyway this one exercise with pynput was so timeconsuming, that i am glad to have found a workaround, and can carry on with the course. Heck , it was frustrating, and hope this comment helps as a motivation to solve this pynput issue. :). I will probably figger something out once i am more mature in python. i' cant affort too google for three weeks on the "é char not recording in pynput", cause it's more important that i have enough time left to do the hands on exersizes. I sure hope there are no more exersizes in the course with the pynput module! Am i complaining? Hell yes !

**Comment by segalion** [comment]
I have tested v.1.4.5 and remains the same reported [14 mar 2019](https://github.com/moses-palmer/pynput/issues/118#issuecomment-472790718)

...what a pitty!

**Comment by segalion** [comment]
Sorry about repeat request.

I have been trying to see inside the code, but I am very confused. I dont really understand why a hook on keyboard, (that it is a listen action) can modify the behaviour of the keyboard. I suppose its because 

I dont understand very well the situation with the "dead keys". Seems that call to OS function 'ToUnicodeEx' make modifications to the keyboard... 

I dont know if it can be possible, but in my opinion could be better disable the detection of key-codes with dead keys (like 'á') (in windows) than modify the behaviour of the keyboard (at least until this can be fixed). 
We could use the keyboard hook for other purposes (i.e. global key binding to launch something), but if you change the behabiour of keyboard, users complain about runnig an application using pynput in windows.

Two more things:

1. can this post https://github.com/microsoft/terminal/pull/3117 help you?

2. People are demanding a "more advanced conbinations" (Ctrl+a, LShift+3 etc.). I have developed a full-feature [global-bind](https://effbot.org/tkinterbook/tkinter-events-and-bindings.htm) over pynput, that works really fine, and easy to manage.

**Comment by moses-palmer** [comment]
I apologise for the lack of feedback on this issue, but I have had very little time to devote to this project lately, and very limited access to systems on which I can actually test it.

I think that dead keys on Windows is the most important issue for this project, but as I have stated before, solving it requires a lot of effort and time. I still believe that `ToUnicodeEx` is the reason for the brokenness.

I will make an effort in the coming days to look into a solution, but if that fails, I think the way forward would be a new major version with a changed API that does not perform as much interpretation of the events provided by the operating system, and thus unfortunately a less platform independent solution.

**Comment by segalion** [comment]
Thanks a lot @moses-palmer 

I appreciate your great work, and I am very interested in solve this bug too.

I will try to publish soon a [bindglobal](https://github.com/moses-palmer/pynput/issues/182#issuecomment-556059808) package over pynput that I thik will raise even more the functionality.

**Comment by segalion** [comment]
Published:
pip install bindglobal

and in https://github.com/segalion/bindglobal

**Comment by moses-palmer** [comment]
I have published a work-in-progress on [fixup-win32-keyboard-listener](https://github.com/moses-palmer/pynput/tree/fixup-win32-keyboard-listener). After cursory testing, it appears to work, but I would very much appreciate testing from everybody here (@schizophrene, @juancroldan, @segalion, @SpecialCharacter).

The one issue I have found is that the state of the _Caps Lock_ key is not respected

**Comment by segalion** [comment]
Dead keys áéîòüÁËÌÒÚ works fine, even with caps-lock activated sends correct case.
~ (alt-gr+4 + space) works fine too

Problems are with { and [ (altgr+'{' or altgr+'['), that makes:

ERROR:pynput.keyboard.Listener:Unhandled exception in listener callback
Traceback (most recent call last):
  File "C:\Users\t148888\AppData\Local\Programs\Python\Python36\lib\site-packages\pynput\_util\__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "C:\Users\t148888\AppData\Local\Programs\Python\Python36\lib\site-packages\pynput\keyboard\_win32.py", line 235, in _process
    key = self._event_to_key(msg, vk)
  File "C:\Users\t148888\AppData\Local\Programs\Python\Python36\lib\site-packages\pynput\keyboard\_win32.py", line 268, in _event_to_key
    msg in self._PRESS_MESSAGES))
  File "C:\Users\t148888\AppData\Local\Programs\Python\Python36\lib\site-packages\pynput\keyboard\_base.py", line 50, in __init__
    'COMBINING ' + unicodedata.name(self.char))
KeyError: "undefined character name 'COMBINING LEFT CURLY BRACKET'"



and 



ERROR:pynput.keyboard.Listener:Unhandled exception in listener callback
Traceback (most recent call last):
  File "C:\Users\t148888\AppData\Local\Programs\Python\Python36\lib\site-packages\pynput\_util\__init__.py", line 162, in inner
    return f(self, *args, **kwargs)
  File "C:\Users\t148888\AppData\Local\Programs\Python\Python36\lib\site-packages\pynput\keyboard\_win32.py", line 235, in _process
    key = self._event_to_key(msg, vk)
  File "C:\Users\t148888\AppData\Local\Programs\Python\Python36\lib\site-packages\pynput\keyboard\_win32.py", line 268, in _event_to_key
    msg in self._PRESS_MESSAGES))
  File "C:\Users\t148888\AppData\Local\Programs\Python\Python36\lib\site-packages\pynput\keyboard\_base.py", line 50, in __init__
    'COMBINING ' + unicodedata.name(self.char))
KeyError: "undefined character name 'COMBINING LEFT SQUARE BRACKET'"


Thanks for the effort.

**Comment by moses-palmer** [comment]
What keyboard layout do you use? For me, typing `'{'` is done by pressing <kbd>altgr+7</kbd>. Does this happen without you pressing any dead characters, or does it happen after you have pressed one?

Unfortunately it works here...

**Comment by segalion** [comment]
Sorry. Spanish keyboard. '{' and '[' are exactly altgr + dead Keys ` and ' for accents.

**Comment by akiratakasaki** [comment]
Yep, like I mentioned before, pynput does not support all keyboards. I am using A belgian keyboard, and even in belgium alone we have two different types of azerty keyboards, just like the netherlands have more then one qwerty keyboards. Hope this helps

**Comment by moses-palmer** [comment]
I have force-pushed changes to [fixup-win32-keyboard-listener](https://github.com/moses-palmer/pynput/tree/fixup-win32-keyboard-listener), and I have verified that on my system, a Spanish keyboard layout works as expected.

Changes:
*  Correctly determine whether a key-press corresponds to a dead key.
*  Allow changing keyboard layout at runtime.

Remaining issues:
*  The state of _Caps Lock_ is still not respected.
*  I have noticed that when I change to a Spanish layout at runtime, `'{'` and `'}'` do not get a character mapping, only a virtual key code mapping.

I would very much appreciate that you test this.

**Comment by SpecialCharacter** [comment]
Sorry to ask that, but how do I install the fixup? pip install ...?

**Comment by moses-palmer** [comment]
Ah, sorry!

You will have to clone this repository:
```bash
# Possibly inside a virtualenv
git clone https://github.com/moses-palmer/pynput
cd pynput
git checkout fixup-win32-keyboard-listener
python setup.py install
```

**Comment by segalion** [comment]
{ [ GúÜâáÄÂàãù ] }

**### All dead keys (´`^¨~), and their no-dead version (altgr+dead_key) works like a charm in spanish keyboard with latest  fixup-win32-keyboard-listener versión**

Lots of thanks for your great effort solving this.

I would like to give this project more than one star.

**Comment by SpecialCharacter** [comment]
When I copy your Global hotkey snippet into my code, it says:

hotkey = keyboard.HotKey(
AttributeError: 'Controller' object has no attribute 'HotKey'

**Comment by moses-palmer** [comment]
@SpecialCharacter, that is probably because you have instantiated a `pynput.keyboard.Controller` as `keyboard`; that will shadow the binding to the *pynput* module in the current scope.

**Comment by SpecialCharacter** [comment]
Yes, I have
keyboard = Controller().
So how to remediate that? I still need the Controller to watch the keyboard...

**Comment by moses-palmer** [comment]
Give it another name, like `keyboard_controller = keyboard.Controller()`.

**Comment by SpecialCharacter** [comment]
Erm, now it says
AttributeError: module 'pynput.keyboard' has no attribute 'type'.

I have:
from pynput import keyboard
from pynput.keyboard import Key, Controller
from pynput.keyboard import KeyCode
from pynput.keyboard import Listener
keyboard_controller = keyboard.Controller()
