### ISSUE TITLE
Need Help: Getting values like "!@#$%^&*()_+?><:{}"

### ISSUE THREAD

**Issue by Ming-desu** [moses-palmer/pynput#129]
I need help in getting the special characters or shift + _key_ values, I have read some of the issues but I can't found any solution to my problem. Please enlighten me up. Thank you!

**Comment by michaelelcat** [comment]
Also looking for help with this.

**Comment by moses-palmer** [comment]
Do you by any chance use *OSX*? If so, could you please test [this branch](https://github.com/moses-palmer/pynput/tree/fixup-osx-keyboard-listener) and see if it solves your issue?

**Comment by SpecialCharacter** [comment]
@Ming-desu and @michaelelcat does it work for you now?

I "solved" it with str.maketrans(intab, outtab), but of course then it is not transferable between different keyboard layouts. 
Also deadkeys will not work because (at least under Windows) the system will wait until a second physical key is pressed.

**Comment by DeeJayhX** [comment]
@Ming-desu if this resolved you issue, can you close it please?
