### ISSUE TITLE
[macOS] Listening c becomes ç when Command is pressed

### ISSUE THREAD

**Issue by xinhuang** [moses-palmer/pynput#134]
Hi,

I tried to listen for `Command-c` (copy) keyboard event on macOS 10.14.1 with Python 3.7.1, but I found that with `Command` being pressed, `c` becomes `ç` (notice the little tail).

But if the `Command` key is release earlier than `c` key, inside `on_release` the key becomes a `c` instead of `ç`.

I am using a Japanese keyboard layout macOS. Would this be the reason? Or what else would be the reason here? How should I properly handle the `Command-c` shortcut?

Thanks!

```python
from pynput import keyboard
Key = keyboard.Key

# FIXME: Why it is ç but not c? Where does the tail come from?
SHORTCUTS = [{Key.cmd, keyboard.KeyCode(char='ç')}]

pressed = set()


def on_press(key):
    print('press', key)
    if any([key in combo for combo in SHORTCUTS]):
        pressed.add(key)
        if any(all(k in pressed for k in combo) for combo in SHORTCUTS):
            print('pressed')


def on_release(key):
    print('release', key)
    if any([key in combo for combo in SHORTCUTS]):
        pressed.remove(key)


with keyboard.Listener(
        on_press=on_press,
        on_release=on_release) as listener:
    listener.join()
```

**Comment by moses-palmer** [comment]
Thank you for your report.

I looked into this, and found an old comment about changing the way keyboard events are translated to actual characters on *OSX*, and implemented a test [here](https://github.com/moses-palmer/pynput/tree/fixup-osx-keyboard-listener). When I run it with your snippet, it appears to work.

Do you have the opportunity to test this? If it solves your issue, I will merge and make a new release.

**Comment by xiebruce** [comment]
@moses-palmer I got this issue too, totally can use command button, I install pynput by using `pip3`, can I ask when will you release the solved version to `https://pypi.org/` ?

**Comment by moses-palmer** [comment]
I just made the release, *1.4.2*.

I never got any feedback on whether the branch actually fixed the issue, but my limited testing at least hinted at that.

**Comment by xiebruce** [comment]
@moses-palmer I update to the new version, the issue was solved, but there is still an issue(I did not check windows, but mac has an issue), it seems that `alt` and `cmd` in 1.4.2 is just swapped compare to the old version 1.4，now button `alt` in 1.4.2 acting like button `cmd` in 1.4, I can't set the key combination to something like `shift+alt+u` or `alt+E`, as long as `alt` is contain , the key combination is  not going to work. If I press `alt` and hold it then press any character, the character is not the original character, can you believe the following symbol is representing `A B C D E F G` respectively?
![image](https://user-images.githubusercontent.com/13575500/54836792-e8588e80-4cff-11e9-9f4e-2b092b7a01ac.png)

So, this is still an issue, I think you have to deal with this issue on macOS specifically.

The following 26 symbols are refer to 26 lowercase English character when I hold `alt`:
```
2019-03-23 00:24:56,628: 'å'
2019-03-23 00:24:58,248: '∫'
2019-03-23 00:24:58,788: 'ç'
2019-03-23 00:24:59,024: '∂'
2019-03-23 00:24:59,283: <14>
2019-03-23 00:25:00,520: 'ƒ'
2019-03-23 00:25:00,723: '©'
2019-03-23 00:25:01,736: '˙'
2019-03-23 00:25:02,523: <34>
2019-03-23 00:25:02,827: '∆'
2019-03-23 00:25:03,086: '˚'
2019-03-23 00:25:03,873: '¬'
2019-03-23 00:25:04,143: 'µ'
2019-03-23 00:25:04,379: <45>
2019-03-23 00:25:05,381: 'ø'
2019-03-23 00:25:05,572: 'π'
π2019-03-23 00:25:06,393: 'œ'
2019-03-23 00:25:07,294: '®'
2019-03-23 00:25:08,182: 'ß'
2019-03-23 00:25:08,812: '†'
2019-03-23 00:25:09,915: <32>
2019-03-23 00:25:10,533: '√'
2019-03-23 00:25:11,085: '∑'
2019-03-23 00:25:12,007: '≈'
2019-03-23 00:25:12,727: '¥'
2019-03-23 00:25:13,267: 'Ω'
```

The following 26 symbols are refer to 26 uppercase English character when I hold `alt`:
```
2019-03-23 00:28:38,496: 'Å'
2019-03-23 00:28:43,537: 'ı'
2019-03-23 00:28:46,000: 'Ç'
2019-03-23 00:28:46,270: 'Î'
2019-03-23 00:28:46,507: '´'
2019-03-23 00:28:47,272: 'Ï'
2019-03-23 00:28:47,598: '©'
2019-03-23 00:28:48,419: 'Ó'
2019-03-23 00:28:49,589: 'ˆ'
2019-03-23 00:28:49,826: 'Ô'
2019-03-23 00:28:50,084: '˚'
2019-03-23 00:28:50,501: 'Ò'
2019-03-23 00:28:51,479: 'Â'
2019-03-23 00:28:51,873: '˜'
2019-03-23 00:28:53,077: 'Ø'
2019-03-23 00:28:53,302: '∏'
2019-03-23 00:28:54,101: 'Œ'
2019-03-23 00:28:54,944: '®'
2019-03-23 00:28:55,518: 'Í'
2019-03-23 00:28:56,070: '†'
2019-03-23 00:28:57,037: '¨'
2019-03-23 00:28:57,813: '√'
2019-03-23 00:28:58,387: '∑'
2019-03-23 00:28:59,433: '≈'
2019-03-23 00:29:00,131: 'Á'
2019-03-23 00:29:00,716: 'Ω'
```

Because macOS's special functionality of quick typing above 52 special symbols, I think you have to map these symbols to their original English character, so we can cover the default action, in this way, combinations on macOS with `alt` in it will be work normally, this is my personal opinion, I don't know if there is a better way the solve this issue.

**Comment by moses-palmer** [comment]
I'll first address your issue with strange mappings when pressing <kbd>alt</kbd>: *pynput* is intended as an abstraction over the various ways different platforms handle mouse and keyboard input. As such, the primary interface to events received through listeners and arguments to input generating functions is characters and special keys, such as arrow keys and modifiers.

This means that the character representation submitted along the event is the character being typed, not the glyph printed on the key. To inspect the physical key used to generate the event, you will probably want to check the [`vk`](https://github.com/moses-palmer/pynput/blob/e1c7a358f316c0a78585b230f7f465be013e6529/lib/pynput/keyboard/_base.py#L44) attribute of the event, which is a virtual key code. This, unfortunately, is entirely platform dependent.

Regarding your issue with <kbd>alt</kbd> and <kbd>cmd</kbd> having been swapped, could you please open a new issue and provide some sample code? I'm afraid that I do not fully understand in what context this happens.
