### ISSUE TITLE
Unable to copy currently copied content， only copy the contents of the last Ctrl+C

### ISSUE THREAD

**Issue by DearLM** [moses-palmer/pynput#147]
code：
![image](https://user-images.githubusercontent.com/7251916/55449396-ef37a900-55fd-11e9-874e-184adaf7d152.png)

**Comment by moses-palmer** [comment]
Sorry for the late reply.

Depending on your platform, events may reach your listener before they are handled by the operating system, which means that if you intend to copy the clipboard when it is created by the user pressing <kbd>ctrl+c</kbd>, you will generally capture the previous buffer, since the operating system has not yet reacted to the event.

You may want to execute the copying asynchronously a little bit later.
