### ISSUE TITLE
Keyboard monitoring limited to some windows on Linux

### ISSUE THREAD

**Issue by genericusername3** [moses-palmer/pynput#151]
Well, the title describes the issue pretty well. While the events are correctly handled when windows like Chromium are in focus, other windows like Sublime Text or Gnome Terminal seem not to allow that.
I'm running Manjaro Linux 18.0.4 with GNOME 3.32.0 (on Wayland)
Any idea on why that might be happening or what I could do to fix that?

**Comment by moses-palmer** [comment]
Sorry about the long delay!

This is unfortunately expected when running under *Wayland*; only windows launched through *XWayland*, (such as Chromium) will work, since *pynput* is limited to *X* on Linux. Issue #184 would solve this, but requires quite a lot of effort to implement, and would require launching the monitoring application as *root*.
