### ISSUE TITLE
determine whether the WM_KEYDOWN message indicates the first down transition or a repeated down transition

### ISSUE THREAD

**Issue by redstoneleo** [moses-palmer/pynput#158]
According  to the [MSDN doc](https://docs.microsoft.com/zh-cn/windows/desktop/inputdev/wm-keydown), 
> If the keystroke is held long enough, multiple messages are sent.

> Because of the autorepeat feature, more than one WM_KEYDOWN message may be posted before a WM_KEYUP message is posted. The previous key state (bit 30) can be used to determine whether the WM_KEYDOWN message indicates the first down transition or a repeated down transition.

I wonder how to get the lParam parameter to implement the feature ?

**Comment by moses-palmer** [comment]
_pynput_ does not use the `WM_KEYDOWN` or `WM_KEYUP` messages; rather, it uses a lower level input system where the event is sent by means of a [`KBDLLHOOKSTRUCT`](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-tagkbdllhookstruct).

Unfortunately, this struct does not contain any information about whether the event is repeated, so in order to realise this feature request, _pynput_ would have to maintain a buffer with the previous state of every key on the keyboard, and unless this turns out to be a common requested feature, I think that would be a little too much overhead.

Please note, however, that #49 may require that anyway. In any case, I will close this issue and revisit it when that issue has been resolved---note its age though.
