### ISSUE TITLE
[Windows] Having issues with (Key.shift) in some shortcuts

### ISSUE THREAD

**Issue by caiobsilva** [moses-palmer/pynput#160]
I'm writing a simple script to manage some screens. At one point of it, I want to move an image to the second screen and make it fullscreen, and so I use
```
keyboard.press(Key.cmd)
keyboard.press(Key.shift)
keyboard.press(Key.right)
keyboard.release(Key.cmd)
keyboard.release(Key.shift)
keyboard.release(Key.right)
time.sleep(1)
```
and
```
keyboard.press(Key.cmd)
keyboard.press(Key.shift)
keyboard.press(Key.enter)
keyboard.release(Key.cmd)
keyboard.release(Key.shift)
keyboard.release(Key.enter)
```

The first function doesn't work as expected. Instead of moving the window to the second screen, it snaps it to the right half of the first screen, as if the keys cmd + right were being pressed. The second function, however, works just fine. Any suggestion on what may be causing this?

**Comment by moses-palmer** [comment]
Thank you for your report.

This appears to be related to #113, since the virtual state of shift is not respected. The code for the keyboard controller on _Windows_ is the simplest of all platforms, so there is unfortunately not much to work with.

I any case, I will close this issue and let any further discussion happen in the issue mentioned above.
