### ISSUE TITLE
Mouse handling does not work in latest master

### ISSUE THREAD

**Issue by russelg** [moses-palmer/pynput#17]
I upgraded to latest master so I could try fix that other issue, and it is now unable to process any mouse input.

I ran the test suite, however everything failed.

![errors](https://sgfc.co/pyTPA.png)

Running Windows 7, 64-bit.
My python install in that picture is 32-bit 2.7.10.

I tried both Python 2.7 and 3.5, both failing.
The tests work fine for the version currently on pypi.

**Comment by moses-palmer** [comment]
Thanks for the report. I am playing a bit with the event API on *win32*, and the commit that you have tested had the unfortunate default value of blocking all events system-wide by default unless an event filter was supplied.

I have changed the API slightly to use saner returns values, and require an explicit method call to suppress events globally; this issue is fixed in the current master.
