### ISSUE TITLE
break cycle by key

### ISSUE THREAD

**Issue by tierline1** [moses-palmer/pynput#197]
i want to break cycle by pressing page_down like this, but no effect, help me pls correct implementation

```
from pynput.keyboard import Key, Listener
import time

reset = 0

def on_press(key):
    global reset    
    if key == Key.page_up:
        print('start proc')
        proc()
    if key == Key.page_down:
        reset = 1
    if key == Key.esc:
        # Stop listener
        return False

def proc():
    while true:
        time.sleep(2)
        print('inside proc..')
        if reset == 1:
            break

with Listener(on_press=on_press) as listener:
    listener.join()
```

**Comment by moses-palmer** [comment]
As noted in [the documentation](https://pynput.readthedocs.io/en/latest/keyboard.html#the-keyboard-listener-thread), you cannot have long running procedures in a listener callback, as all events will generally be handled by the same thread, and that thread will be blocked until your callback returns.

One idea is to replace `listener.join()` with something like `wait_for_pgup(); proc(); listener.join()`, where `wait_for_pgup` could wait for a `threading.Condition` notified by your listener callback.

**Comment by segalion** [comment]
Try  [bindglobal](https://github.com/segalion/bindglobal)

`pip install bindglobal`

- It work fine with long running procedures, because internally It creates a new thread for running your callbacks, so if you take long time inside callback all keystrokes bindings will be enqueued

- There are another option to work fine with tkinter gui mainthread: if you create GlobalBind with a tkinter widget, callbacks will run on mainthread, so you could thread-safe call tkinter inside callbacks.

**Comment by tierline1** [comment]
thanks, guys! I'll found simple solution
just start proc() in thread and it works properly:
```
t = threading.Thread(target=proc)
t.start()
```
