### ISSUE TITLE
Propose: Registration method to create methods for specific methods

### ISSUE THREAD

**Issue by JokeNeverSoke** [moses-palmer/pynput#212]
~~I was hoping to write a self-defined keyboard registration~~ (not important)

The thing is:
**Would it be possible to map specific keys to specific functions (and suppress those keypresses) without effecting or touching other keypress?**
Just a proposal

**Comment by moses-palmer** [comment]
Not in a platform-independent manner unfortunately, since the platforms differ too much in how this would be performed.

For keyboard suppression, look into the keyword arguments `win32_event_filter` for *Windows* and `darwin_intercept` for *macOS* in the [documentation](https://pynput.readthedocs.io/en/latest/keyboard.html#pynput.keyboard.Listener). Filtered suppression is not supported at all under *X*.
