### ISSUE TITLE
Keyboard listener detects key press differently with and without ctrl modifier (1.6.5)

### ISSUE THREAD

**Issue by ClarinetK622** [moses-palmer/pynput#218]
Hi there,
When using the keyboard listener to detect keystrokes, having control pressed makes the key code generated by new keys difficult to interpret. For instance, when ctrl is held, pressing 'a' gives keycode '\x01'. 'b' gives '\x02' 'm' gives '\r', etc. For other keys the key code is even more difficult to understand, for instance ';' returns '<186>'. Is this intentional? If so, is there a conversion chart or something that allows us to see the normal key name as if the control modifier were not held down?
I'm using pynput to allow users to define custom hotkeys. This problem arises when users enter hotkeys (involving ctrl) and I try to interpret what keys they are holding down. I imagine it could cause problems in other areas as well.
Much thanks.

**Comment by moses-palmer** [comment]
I just released *pynput 1.6.6* with a fix for the documentation of the `HotKey` helper class. In order to do that, I hade to make a previously private method public: https://github.com/moses-palmer/pynput/blob/340db52441382532c6ab649f2c9275d76ae01ec4/lib/pynput/keyboard/_base.py#L680.

You should be able to use this to ignore the modified key codes returned by _Windows_.

**Comment by ClarinetK622** [comment]
Works like a charm, thanks!
