### ISSUE TITLE
Q: What is meant by "non-blocking" in the documentation?

### ISSUE THREAD

**Issue by GeorgeCiesinski** [moses-palmer/pynput#221]
I am trying to understand the [handling the keyboard](https://pynput.readthedocs.io/en/latest/keyboard.html) section of the documentation, but I see a term "non-blocking" and I don't see it defined in the documentation. I understand that this library uses a thread, but I'm not sure how these two below examples (from the documentation) are different: 

```
# Collect events until released
with keyboard.Listener(
        on_press=on_press,
        on_release=on_release) as listener:
    listener.join()

# ...or, in a non-blocking fashion:
listener = keyboard.Listener(
    on_press=on_press,
    on_release=on_release)
listener.start()
```

Will pynput work the same with both examples, or is something going to change? 

I need to know this because I'm trying to use this with a Tkinter app, but the two libraries use threads and I have been unsuccessful in using the pynput listener at the same time as the tkinter mainloop. I'm hoping this is the solution.

**Comment by moses-palmer** [comment]
The first example will block execution of the current thread until the listener is stopped because of the call to [`listener.join()`](https://docs.python.org/3/library/threading.html#threading.Thread.join), whereas the second will continue past the call to [`listener.start()`](https://docs.python.org/3/library/threading.html#threading.Thread.start).

The behaviour of using a listener in a `with`-statement is documented [here](https://pynput.readthedocs.io/en/latest/keyboard.html#pynput.keyboard.Listener).

**Comment by moses-palmer** [comment]
I have updated the documentation, so I will now close this issue.

**Comment by GeorgeCiesinski** [comment]
Thanks for the info, it was very helpful.
