### ISSUE TITLE
About <cmd>?

### ISSUE THREAD

**Issue by jizhihaoSAMA** [moses-palmer/pynput#227]
```
list1 = keyboard.HotKey.parse("<cmd>+<shift>+s")
Controll = keyboard.Controller()
for i in list1:
    Controll.press(i)
for i in list1:
    Controll.release(i)
```
"Win+shift+S" can make a screenshot in my Windows 10.But it won't work.

This code could work in my computer,But it doesn't work in other computer.
```
    with Controll.pressed(Key.cmd):
        with Controll.pressed(Key.shift):
            Controll.press('s')
            Controll.release('s')
```

What should I do?

**Comment by moses-palmer** [comment]
Thank you for your report.

As to why your first example does not work, I think it might be because [`pynput.keyboard.HotKey.parse`](https://github.com/moses-palmer/pynput/blob/64f885deb04f264d749d45cbab486dd0e833e107/lib/pynput/keyboard/__init__.py#L141) returns a `set`:

```python
from pynput import keyboard

# Prints Key.shift 's' Key.cmd on my system, since the order of items in a set is
# undefined
print(' '.join(str(k) for k in keyboard.HotKey.parse('<cmd>+<shift>+s')))
```

I am a bit uncertain about the reason for the second example. What are the differences between the two systems?

**Comment by jizhihaoSAMA** [comment]
My system is win10,the another one is win10,too.

Is it possible to change the returned type is ``list`` instead of ``set`` in the future?Or add a new function to return a ``list``?

**Comment by moses-palmer** [comment]
Since this has landed in *master*, I will close this issue.
