### ISSUE TITLE
Is Pynput able to be asynchronous? 

### ISSUE THREAD

**Issue by Braythor** [moses-palmer/pynput#243]
Working in some twitch bot code, doing an async and await for a command. You probably aren't familiar with this, so I'll drop it below:

`@bot.command(name='w')
async def w(ctx):
    await keyboard.press('w')
    await keyboard.release('w')
    print("Pressing W!")`

Can you await keyboard.press&release?

Thanks for your time.

**Comment by moses-palmer** [comment]
*pynput* does not out-of-the box support _async-await_. This is because not all versions of *Python* supported by this library support the `async` keyword, and monkey-patching it on top would clutter the API.

Having said that, I do not really understand your example: do you want to make the control classes asynchronous? Most supported platforms provide the underlying functionality as synchronous functions, with the underlying assumption that calling them will be quick. Have you found these methods to require `async`'ness?

**Comment by moses-palmer** [comment]
I will close this, but please reopen if you think that is not correct.
