### ISSUE TITLE
Limits in keyboard monitoring ?

### ISSUE THREAD

**Issue by Matthix7** [moses-palmer/pynput#249]
Hi,

I encounter an issue that I can only explain as being a limit of pynput while monitoring my azerty keyboard: for some combinations of 3+ keys pressed, there can be only the two first of them being detected and taken into account in the on_press function. 
For instance, if I press simultaneously ['y'+'j'+'o'], the 'o' is never detected whereas it is when pressed alone. ['j'+'o'] or ['y'+'o'] combinations are treated as expected. 
Moreover, this only happens with some combinations and pynput succeeded in detecting all letters in 4+ letters combinations so I do not understand where the problem can come from.
Have you ever experienced this ?

Anyway, thanks for this work !

**Comment by moses-palmer** [comment]
Thank you for your report.

I think you have run into the limits of the hardware to be honest. I've never been able to detect more than three keys simultaneously---not even in the days of MS-DOS 6 where you had unrestricted access to the hardware. I remember this being stated as a fact, so I'm actually surprised that you managed to detect more keys.

I will close this issue as I don't think it pertains to *pynput*. If you think otherwise, please reopen it.
