### ISSUE TITLE
mouse press left button 

### ISSUE THREAD

**Issue by Nobys1** [moses-palmer/pynput#282]
Hello! I was getting this issue when running this program:

  File "c:/Users/ME/Desktop/Untitled-2.py", line 8, in <module>
    mouse.press(Button.left)
  File "C:\Users\ME\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pynput\keyboard\_base.py", line 379, in press
    if resolved.is_dead:
AttributeError: 'NoneType' object has no attribute 'is_dead'

This is the code:

from pynput.mouse import Button, Controller

from pynput.keyboard import Key, Controller

while True:
    mouse = Controller()
    mouse.position = (642, 464)
    mouse.press(Button.left)
    mouse.release(Button.left)
    keyboard = Controller()
    keyboard.press(Key.ctrl)
    keyboard.press("v")
    keyboard.release("v")
    keyboard.release(Key.ctrl)
    mouse.position = (750, 506)
    mouse.press(Button.left)
    mouse.release(Button.left)

**Comment by moses-palmer** [comment]
Thank you for your report.

Your code sample shadows the mouse controller class on line 3, so both your mouse and keyboard controllers are instances of `pynput.keyboard.Controller`; that is why `Button.left` is not resolved.

The error you experience, however, is due to a bug in *pynput*; it should definitely check the return value from `self._resolve` on line [364](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_base.py#L364).

**Comment by moses-palmer** [comment]
This was addressed in e6c1625b.
