### ISSUE TITLE
How to hide inputs from the OS?

### ISSUE THREAD

**Issue by SpecialCharacter** [moses-palmer/pynput#291]
I want to assign `cmd_r` to a new function.
Unfortunately, it also shows its 'old' behavior (opening some menu, which interferes with the new function).
How to hide such inputs from the OS?
I employed the keyboard listener in the blocking version, but it does have no effect.

**Comment by moses-palmer** [comment]
The only way to hide key presses from the operating system is to pass the `suppress=True` flag to the listener constructor.

This will, however, suppress *all* keyboard events, and should only be used for short-lived contexts, since it forces you to mock a keyboard for events that you do not want to suppress using a `Controller` instance; this is not trivial.

**Comment by SpecialCharacter** [comment]
Thanks! Can you give an example?

Is there no other way to suppress the 'old' behavior of _only_  `cmd_r`?

**Comment by moses-palmer** [comment]
You will find a rough blueprint in my response to #290.

Globally suppressing all events is unfortunately the only method supported by all platforms; on *macOS* and *Windows* you can use platform specific callbacks to selectively suppress input events.
