### ISSUE TITLE
Intercepting keystrokes without forwarding them

### ISSUE THREAD

**Issue by adiron** [moses-palmer/pynput#3]
Hello there

I'm trying to build a basic "remapper" that takes keyboard input and relays it differently based on modes/chords or other variables.

While I mostly have a system in place which can read keystrokes and interpret them (works well so far) I haven't been able to disable the keystrokes for other purposes. i.e: If I get the keystroke for A, I can't prevent the OS from forwarding that A keystroke to the window in focus even though my program may want to send the keystroke for B or Tab or anything else.

I wonder if there's a way to make this work at least in macOS. I know that the Plover project is written in Python, and it might have the answers. I'm not so good with this stuff unfortunately so I can't really tell, but [I think here's how Plover does it on macOS](https://github.com/openstenoproject/plover/blob/master/plover/oslayer/osxkeyboardcontrol.py#L177-L233) as well as [Windows](https://github.com/openstenoproject/plover/blob/master/plover/oslayer/winkeyboardcontrol.py#L258-L280).

Would appreciate any hints.

Thanks
Adi Ron.

**Comment by moses-palmer** [comment]
Hi,

I think this could be solved for *OSX* by modify the flags passed to [CGEventTapCreate](https://developer.apple.com/reference/coregraphics/1454426-cgeventtapcreate). They can be found [here](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/_util/darwin.py#L223).

If you pass `0` instead of `Quartz.kCGEventTapOptionListenOnly` as the third argument, you should be able to intercept keys. There is currently no way to do this through the library, but I just made a commit where the creation of the event tap is done by a distinct method; if you override [pynpyt._util.darwin.ListenerMixin._create_event_tap](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/_util/darwin.py#L218) to set the flags and [pynpyt._util.darwin.ListenerMixin._handle](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/_util/darwin.py#L239) to modify the event, you should be able to create what you want.

**Comment by adiron** [comment]
I'll try to make this toggleable and open a PR if I succeed.

**Comment by moses-palmer** [comment]
Great!

This repository does not have a `CONTRIBUTING.md`, but please try to follow these simple guidelines:

*  **Use pylint**. Run `python setup.py lint` before maing any modifications, and make sure that the *pylint score* does not decrease. I personally use *atom* as editor, and it has a pylint plugin; I am sure your preferred editor has one as well.
*  **Please keep in mind that *pynput* has *darwin*, *win32* and *xorg* backends.** Ensure that you do not introduce breaking changes.

A possible way to implement what you want is as follows:

*  Introduce a new flag parameter to the `Listener` constructor---`intercept` or similar---to tell the backend that interception is wanted.
*  If intercepting, try to modify the propagated event with the return value of the handler function as called [here](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_darwin.py#L200), [here](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_darwin.py#L204) and other locations in the same method. I suggest you use a [pynput.KeyCode](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_base.py#L37) as return value, and perhaps ignore interceptions if the handler returns `None`.
*  For now, raise `NotImplementedError` if `intercept` is set for backends other than *darwin*.

The tricky part will be to convert the `KeyCode` to what the `CGEvent` contains; the inverse of [pynput.keyboard._darwin.Listener._event_to_key](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_darwin.py#L228).

Thank you for your effort!

**Comment by moses-palmer** [comment]
FYI, this functionality has been added to the [master branch](https://github.com/moses-palmer/pynput/commit/6bd64ad88b27da6f114f4eb52cd6e6d31ac36901).

**Comment by dumblob** [comment]
@pssolanki111 do you have your code public somewhere? I would like to take a look before diving in the depths of the key mappings hell :wink:.

**Comment by pssolanki111** [comment]
hey @dumblob I actually dropped working on that project due to a change in requirements. I only did some tests around it and I remember I came across some roadblocks. Below is the piece of code I wrote for tests, which as I mentioned, couldn't continue writing more to.

The use case for the below tests was a re-mapper program which would intercept keys in real time and type in `trans-litted` variants of letters based on a pre defined mapping.

Also I think you need `darwin_intercept` function only for OSX. For other OS, you should be able to do  fine without it (IIRC)

Also If i remember well, the issue I faced was with `re-mapped` key press. It appeared to me that the suppressor was suppressing the inputs I was trying to enter programmatically. And the requirements changed before I figured this out.
```py
from pynput.keyboard import Listener, Key, KeyCode, Controller
import Quartz

PATH = '/home/pssolanki/mappings.json'

controller = Controller()

def darwin_intercept(event_type, event):
    length, chars = Quartz.CGEventKeyboardGetUnicodeString(
        event, 100, None, None)
    if length > 0 and chars == 'x':
        # Suppress x
        return None
    elif length > 0 and chars == 'a':
        # Transform a to b
        Quartz.CGEventKeyboardSetUnicodeString(event, 1, 'b')
    else:
        return event

def key_pressed(key):
    if not isinstance(key, KeyCode):
        print('l')
        controller.press(key)
    print(f'pressed: {key}')

def key_released(key):
    print(f'released: {key}')

with Listener(on_press=key_pressed, on_release=key_released, suppress=True) as listener:
    listener.join()
```

**Comment by dumblob** [comment]
Ok, thanks anyway @pssolanki111 !
