### ISSUE TITLE
remap key

### ISSUE THREAD

**Issue by arikgelman** [moses-palmer/pynput#309]
Hi
Is there a way in pynput to remap a key, i.e. When you press the "backspace" key it will press the "delete" key instead.

In the keyboard library this can be done as follows

```
import keyboard

keyboard.remap_key("backspace","delete")

```

Perhaps this can be done by suppressing the "delete" key and setting the functionality under the "on_press" function. But I couldn't find a way to suppress a single key in pynput.

Thanks

**Comment by SpecialCharacter** [comment]
What about

```
def on_hotkey_"backspace"(): # look for the right keycode
keyboardcontroller.type("delete")

		HOTKEYS = [
			keyboard.HotKey(keyboard.HotKey.parse('"backspace"'), on_hotkey_"backspace"), # look for the right keycode
]
```
?

**Comment by moses-palmer** [comment]
Thank you for your report, and sorry for the late response.

This is not really possible to do in *pynput* in a clean manner. Previous attempts have all subtly broken the system in one way or another, since this need proper low-level support from the library. *keyboard* appears to sport that, so I would go with that library.
