### ISSUE TITLE
How to detect key being held down instead of a press?

### ISSUE THREAD

**Issue by Miail** [moses-palmer/pynput#36]
I am currently working on implementing a feature which "does something while a key is being held down"..  As I understand pynput, it seems impossible to implement such feature? or am i missing something?

This implementation:
```
from pynput import keyboard

def on_press(key):
    if key == keyboard.Key.cmd_l:
        try:
            print('- Started recording -'.format(key))
        except IOError:
            print "Error"
    else:
        print('incorrect character {0}, press cmd_l'.format(key))


def on_release(key):
    print('{0} released'.format(key))
    if key == keyboard.Key.cmd_l:
        print('{0} stop'.format(key))
        keyboard.Listener.stop
        return False


with keyboard.Listener(on_press=on_press, on_release=on_release) as listener:
    listener.join()

```

Only detect one press, also when the key is being held down.. It doesn't seem to read the stream.. 

I thought maybe the use of a while loop would help, also giving the way the problem is stated, so i tried this... 

```
from pynput import keyboard

def on_press(key):
    while key == keyboard.Key.cmd_l:
        try:
            print('- Started recording -'.format(key))
        except IOError:
            print "Error"
    else:
        print('incorrect character {0}, press cmd_l'.format(key))


def on_release(key):
    print('{0} released'.format(key))
    if key == keyboard.Key.cmd_l:
        print('{0} stop'.format(key))
        keyboard.Listener.stop
        return False

with keyboard.Listener(on_press=on_press, on_release=on_release) as listener:
    listener.join()
```

Which resulted in being stuck in a while loop.. and not come outside.. 
can the library be used like this, can it detect  "a key being held down"?

**Comment by moses-palmer** [comment]
The operating system, or input handling system, will generally only
generate events upon press and release.

You will probably have to decide on a reasonable time out, schedule a timer
with your task and cancel it if the key is released.

On 4 Jul 2017 15:12, "Miail" <notifications@github.com> wrote:

I am currently working on implementing a feature which "does something
while a key is being held down".. As I understand pynput, it seems
impossible to implement such feature? or am i missing something?

This implementation:

from pynput import keyboard

def on_press(key):
    if key == keyboard.Key.cmd_l:
        try:
            print('- Started recording -'.format(key))
        except IOError:
            print "Error"
    else:
        print('incorrect character {0}, press cmd_l'.format(key))


def on_release(key):
    print('{0} released'.format(key))
    if key == keyboard.Key.cmd_l:
        print('{0} stop'.format(key))
        keyboard.Listener.stop
        return False


with keyboard.Listener(on_press=on_press, on_release=on_release) as listener:
    listener.join()


Only detect one press, also when the key is being held down.. It doesn't
seem to read the stream..

I though maybe the use of a while loop would help, also giving the way the
problem is stated, so i tried this...

from pynput import keyboard

def on_press(key):
    while key == keyboard.Key.cmd_l:
        try:
            print('- Started recording -'.format(key))
        except IOError:
            print "Error"
    else:
        print('incorrect character {0}, press cmd_l'.format(key))


def on_release(key):
    print('{0} released'.format(key))
    if key == keyboard.Key.cmd_l:
        print('{0} stop'.format(key))
        keyboard.Listener.stop
        return False

with keyboard.Listener(on_press=on_press, on_release=on_release) as listener:
    listener.join()

Which resulted in being stuck in a while loop.. and not come outside..
can the library be used like this, can it detect "a key being held down"?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/moses-palmer/pynput/issues/36>, or mute the thread

**Comment by Miail** [comment]
Sorry?.. Not sure I understand how the timer should be involved, and how on_release should turn it off..

Are thinking of a solution in which `on_press` and `on_release` toggle a boolean, and the the boolean either start/stops an while loop outside the function defintion... if thats the case, how will it update the state of the boolean when it is being stuck inside the while loop?

**Comment by moses-palmer** [comment]
You could use, for example, `threading.Timer`. It has a [cancel](https://docs.python.org/3/library/threading.html#threading.Timer.cancel) method to stop the timer. You could keep a dict of *pynput* keys to timers.

I am currently on a flight, so I can't really help you more; as this is out of scope for this library, I'll close this issue.
