### ISSUE TITLE
After turning .py into .exe, executing script fails: "missing modules"

### ISSUE THREAD

**Issue by SpecialCharacter** [moses-palmer/pynput#367]
I have a similar kind of problem as #362, but only after I turn .py into .exe with pyinstaller or py2exe (Windows 10, python 3.9.2, pyinstaller 4.2).
My .py script itself executes just fine.

Pyinstaller lists ~20 modules as missing, py2exe only four:

  4 missing Modules
  ------------------
? Quartz                              imported from __SCRIPT__
? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? readline                            imported from cmd, code, pdb
? resource                            imported from test.support

Is it an incompatibility between pynput and pyinstaller? Or should I remove my python installation and start from from scratch?

**Comment by moses-palmer** [comment]
Thank you for your report.

This issue is similar to #312 , but none of the modules you list are direct dependencies of *pynput*. The [documentation](https://pynput.readthedocs.io/en/latest/faq.html#when-using-a-packager-i-get-an-importerror-on-startup) contains some hints on how to make *pynput* work with packers, but for information on how to include the other dependencies I have to direct you to the documentation for those tools.
