### ISSUE TITLE
'HOTKEYS' referenced before assignment

### ISSUE THREAD

**Issue by SpecialCharacter** [moses-palmer/pynput#368]
I want to toggle my script, i.e. it runs in the background but has to be activated by a key combination.
However, I run into this:
```
Unhandled exception in listener callback [...]
NameError: free variable 'HOTKEYS' referenced before assignment in enclosing scope
```
When I switch the setting, i.e. _de_-activated upon key combination, everything works fine.

Is this a programming mistake on my side or a bug?

**Comment by moses-palmer** [comment]
Thank you for your report.

To be frank, this is a programming mistake on your part :-) You have probably forgotten a `global` statement on the callback function, since *Python* thinks that `HOTKEYS` should be a local variable and you have not yet bound it.

If this is correct, you will also have an assignment in the callback (`HOTKEYS = ...`). You might want to move this out to another scope, as *pynput* gives you no guarantees about in which thread the callback will execute, and you might introduce race conditions if you modify global state.

I will close this issue, but if your investigation reveals that this is indeed a bug in this library, please reopen.

**Comment by moses-palmer** [comment]
You may want to read up on shipping rules in Python. Here's a link with some information: https://realpython.com/python-scope-legb-rule/

**Comment by SpecialCharacter** [comment]
I tried many things, but nothing worked so far...
My structure is this:
```
Transkription = False
def keyboard_listener():
        global listener
	global Transkription
	global Hotkeys
              if Transkription == True:
                   def on_hotkey_a():
...
                   HOTKEYS = [keyboard.HotKey(keyboard.HotKey.parse('a'), on_hotkey_a)]
            else:
                 pass

	def press_callback(key):
		global Transkription
		global Hotkeys
		if Transkription == True:
			for hotkey in HOTKEYS:
				hotkey.press(listener.canonical(key)) # Handle pressed keys
		else:
			pass
```

**Comment by SpecialCharacter** [comment]
Oh, I just realized it should probably be `global HOTKEYS`, not Hotkeys.
Now the error message is `NameError: name 'HOTKEYS' is not defined`.

**Comment by SpecialCharacter** [comment]
Put the HOTKEYS list on the start, but with no hotkeys inside.
Program works (yahoo!), but doesn't print hotkeys when activated...

**Comment by SpecialCharacter** [comment]
Had to change True into False. Not sure why, but now it works as intended :)
Programming mistake finally solved!
