### ISSUE TITLE
Logging while in game

### ISSUE THREAD

**Issue by AlexMuresan** [moses-palmer/pynput#376]
**Description**
I'm trying to monitor mouse movements, clicks and scrolls while playing different games. Right now I'm trying to implement it for CS:GO but it seems like the game is taking control of the mouse(which makes sense). I was wondering if there's a way to log the mouse movements while playing the game.

So as an example, the mouse logging works while inside the menu, but once the game starts the coordinates switch to (3968.0, -12.0) and remain stuck there. The strange this is that clicks (both presses and releases) are captured, and so is scrolling.

**Platform and pynput version**
Platform: MacOSX Big Sur 11.2.3
pynput version: 1.7.3

**To Reproduce**
The code that I'm using is the same as the example provided by you.

**Comment by moses-palmer** [comment]
Thank you for your report.

I would guess this is caused by the application. An application using *pynput* is able to record events and position the mouse pointer, but so is any other application.

You may want to check out the [`darwin_intercept`](https://pynput.readthedocs.io/en/latest/mouse.html#pynput.mouse.Listener) argument to the mouse listener; it will provide you with the event sent by the operating system, and it may contain more information. See [here](https://github.com/moses-palmer/pynput/blob/c3af9c8132e73ed0a31f5e5c8b6b86e13df1d71e/lib/pynput/mouse/_darwin.py#L175) for some samples on using the event object. Please remember to return the event from your callback, otherwise all input will be suppressed!

**Comment by AlexMuresan** [comment]
I will try that, thank you! 

Another thing I discovered a few days after posting is that CS:GO has an option under mouse settings called 'raw input' if I turn that off it seems like I can track the mouse movements, somehow. However I think what happens while playing is that the game pulls the mouse cursor back at the center of the window so that my coordinates are always returning back to that center point. 

I'll what happens when using the parameters you mentioned.

Cheers!
