### ISSUE TITLE
Supporting higher mouse button numbers

### ISSUE THREAD

**Issue by Ravirael** [moses-palmer/pynput#39]
Mouse buttons with number higher than 9 are indistinguishable from each other on XOrg implementaion of mouse `Listener`. That's of course caused by enum `Button` which doesn't support buttons higher than 9 and thus listener reports `Button.unknown`. 

I cannot see a reason for such limitation. Of course there is a workaround but I believe this should be changed anyway.

Workaround to detect button with number higher than 9 in listener:
```
from pynput import mouse

def number_aware_button(number):
    try:
        button = mouse.Button(number)
    except ValueError:
        button = mouse.Button.unknown
    button.button_number = number
    return button

def on_click(x, y, button, pressed):
    print('Button {0} {1} {2}'.format(
        button,
        button.button_number,
        'pressed' if pressed else 'released')
        )

with mouse.Listener(on_click=on_click) as listener:
    listener._button = number_aware_button
    listener.join()
```

**Comment by moses-palmer** [comment]
Thank you for your report.

The reason that buttons are represented as _enums_ is because of the simplicity of consumption: a simple `if button == Button.left` is enough to check which button was pressed.

At the same time, I realise that the library breaking for arbitrary buttons is... well, bad. Unfortunately your proposed solution does not work; it will modify `Button.unknown.button_number` every time an unknown button is encountered, leading to strange behaviour in multi threaded code.

At the moment, the best solution I can think of is extending [5bddf97 - Added values for button 8 and 9 for Xorg](https://github.com/moses-palmer/pynput/commit/5bddf97e3d42fae042f865634b3ea53491ae81f2) to include even more buttons. While this solution may seem less elegant, there does exist some limitation on the possible number of buttons, so it might not be as bad as it seems.

Another possibility is to create a different, non-enum, class for buttons greater than `Button.button9`. What do you think? I have never used a mouse with more than seven buttons, including the scroll wheel, so I might not be the best judge ;-)

**Comment by Ravirael** [comment]
@moses-palmer My mouse (Logitech MX Performance) has 4 additional buttons numbered as 8, 9, 10, 13. I guess it is some kind of standard numbering scheme. Buttons 8 i 9 work as backward/forward in web browser. The 13 is a "zoom" button and indeed combined with scroll wheel enables zooming in web browser. 

Extending the enum wouId certainly work. I don't know what is the limit (maybe 255 if the number is encoded on one byte?) but it's not 9. I think it is not very difficult to create [enum dynamically](https://stackoverflow.com/a/33690233/3367929) in python without having to list every possible value so you can easily go up to 255 with one loop. 

I think that using another class instead of `Button.unknown` is also an acceptable solution, although it may be a bit counterintuitive that the type of `button` can be either enum or something else.

**Comment by moses-palmer** [comment]
I added buttons up to *30* in *pynput 1.3.7*. Create a new bug report when you get a new mouse :-)
