### ISSUE TITLE
on_release event is not fired when a key is pressed in keyboard Listener [Ubuntu]

### ISSUE THREAD

**Issue by hash3liZer** [moses-palmer/pynput#397]
**Description**
I am currently on Ubuntu. Previously, i have done this on Windows and it worked all fine. But on linux the callback simple isn't called when a key is pressed. 

**Platform and pynput version**
Worked Fine on:
Ubuntu: `21.04`
Pynput: `1.7.3`

**To Reproduce**
The following code is enough to reproduce the bug. It would fine under Windows. But on linux it doesn't fire the `on_release` function: 

```python
from pynput import keyboard

def toprint(key):
    print(str(key))

with keyboard.Listener(
    on_release = toprint 
) as listener:
    listener.join()
```

**Comment by moses-palmer** [comment]
Thank you for your report.

Please see the [platform limitations](https://pynput.readthedocs.io/en/latest/limitations.html#linux) for Linux.

To summarise: keyboard listeners on Linux use either _X_ or _uinput_ as backend. _Ubuntu 21.04_ switched to using _Wayland_ instead of _X_ as display and input server, and the security model of this system is incompatible with input monitors. There exist drafts for protocols adding this support, but as far as I know, none have been accepted by all vendors.

_uinput_ is still an option, but it comes with [additional restrictions](https://pynput.readthedocs.io/en/latest/#forcing-a-specific-backend).
