### ISSUE TITLE
Monitoring keyboard with uinput backend does not work

### ISSUE THREAD

**Issue by FelixRilling** [moses-palmer/pynput#408]
**Description**
Using the `uinput` backend and running the script as root does never fire any keyboard events, both under wayland and XOrg.

**Platform and pynput version**

- Arch Linux (Kernel 5.14.2)
- DE: KDE Plasma 5.22.5
- XOrg server: 1.20.13
- Python: 3.9.7
- pynput: 1.7.3

**To Reproduce**
1) Create a script with the example code from <https://pynput.readthedocs.io/en/latest/keyboard.html#monitoring-the-keyboard>
2) Start the script with root and the environment variables set to `PYNPUT_BACKEND_MOUSE=dummy` and `PYNPUT_BACKEND_KEYBOARD=uinput`
3) Input any keys
4) No logging takes place

**Notes**
- I was only able to test this on one device.
- I confirmed that the backend was determined correctly, as when starting without root, the error message in regards to having to use root is shown.
- I saw the note on <https://pynput.readthedocs.io/en/latest/#forcing-a-specific-backend> regarding limitations of the uinput backend, but it seems like listening to keyboard input should be supported?
- When using the default XOrg backend, everything works.
- I also ran the example code for injecting keys, which did send input events.

**Comment by moses-palmer** [comment]
Thank you for your report.

I have not been able to reproduce your issue, but according to a post on [Stackoverflow](https://stackoverflow.com/a/5188461), this might be caused by _X_ interfering, although the post talks about a _Wacom device_. It appears that you are running your application under X. I myself use _Wayland_, which might be the reason I cannot reproduce.

Have you tried running under Wayland?

**Comment by FelixRilling** [comment]
Thank you for the response!
I did try running it under Wayland (KDE Plasma under Wayland), with the same result (no keyboard events being received).

**Comment by moses-palmer** [comment]
I apologise for this late reply.

*pynput* does not listen to all devices; given the type of listener that is requested (well, only keyboard is supported) it will iterate over all input devices and select the first one with the required capabilities (see [here](https://github.com/moses-palmer/pynput/blob/a6d3450ac61e9c33b786ad569f16898bd6cab349/lib/pynput/_util/uinput.py#L60)).

This suggests that your mouse is found before your keyboard, and since your mouse is capable of keboard events, it will unfortunately be picked.

A workaround is to provide the---for now undocumented---keyword argument `uinput_device_paths`. It should be a list of paths to input devices such as `['/dev/input/event0']`.

**Comment by Fornball** [comment]
Hey, so I'm having the same issue. How does this 

> A workaround is to provide the---for now undocumented---keyword argument `uinput_device_paths`. It should be a list of paths to input devices such as `['/dev/input/event0']`.

translate into a command? Like this?:  
```
sudo env PYNPUT_BACKEND_KEYBOARD=uinput PYNPUT_BACKEND_MOUSE=dummy python3 script.py --uinput_device_paths ['/dev/input/event0']
```

**Comment by moses-palmer** [comment]
`uinput_device_paths` should be specified as a keyword argument to the constructor.
