### ISSUE TITLE
cannot drag 'n drop files/folders after executing keyboard.press(Key.esc)

### ISSUE THREAD

**Issue by bennett-nguyen** [moses-palmer/pynput#432]
**Description**
Executing the line `keyboard.press(Key.esc)` will forbid you from dragging your file around in the File Explorer, the issue won't be resolved even if you closed the program and you'll have to restart your computer in order to drag your file around.

**Platform**
Current platform: Windows 10
Python version: 3.10.0
pynput version: 1.7.5

**Steps To Reproduce**
Create a python file then paste in that file with this:
```py
from pynput.keyboard import Controller, Key

keyboard = Controller()

keyboard.press(Key.esc)
```
Before running this code, open your File Explorer and try to drag a file and drop it to a random directory (or just drag it around), you'll see the icon of that file being dragged by your mouse as expected. Then run the code,  now try to drag your file around again; this time, the icon of your file will quickly disappear as you were dragging it.

**Comment by moses-palmer** [comment]
Thank you for your report.

When you call `pynput.keyboard.Controller.press`, the key will remain pressed until you release it. After your program has run, *Windows* will think that the escape key is pressed, and this will cause Explorer to immediately cancel file dra operations.

The solution is to also call release. Please note that, at least on my system, simply pressing escape on the physical keyboard works as well, as that will eventually cause a key release event.

I will close this issue, as this is the expected behaviour.
