### ISSUE TITLE
optionally block propagation of keyboard events

### ISSUE THREAD

**Issue by m27315** [moses-palmer/pynput#47]
Hi,

I really like your module.  It is very simple to use, and I'm using it to teach Python to middle-schoolers.

Currently, I am using this code as a demonstration (modified only slightly from your docs):

```
#!/usr/bin/env python
from pynput import keyboard
def on_press(key):
    try:
        print('Pressed: {}'.format(key.char))
    except AttributeError:
        print('Special key: {}'.format(key))

def on_release(key):
    print('Release: {}'.format(key))
    if key == keyboard.Key.esc:
        return False

with keyboard.Listener(on_press=on_press, on_release=on_release) as listener:
    while True:
        print(".")
        time.sleep(1.0)
```

It produces output like:

```
$ python test.py 
.
.
aPressed: a
Release: u'a'
.
jPressed: j
.
Release: u'j'
.
```

The problem is that each key event is propagated to the terminal, so it appears in addition to the messages.

When the program finishes, all of the output is again echoed to the bash prompt, like so:

```$ ajadajjjajddjaajajajjajajajjajajajajj```

Can you provide an optional flag or method that blocks propagation of keyboard events after they are handled by pynput?  I want to use this for a simple game, and I want the game to respond to the keyboard as a controller.  I do not want to see the keystrokes echoed to the terminal during the game or after the game.

Thanks!

**Comment by moses-palmer** [comment]
What operating system do you use? This is possible on _Windows_ using [win32_event_filter](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/keyboard/_base.py#L638).

From your hashbang, however, it seems like you are using _Linux_. _Xorg_ unfortunately does not allow suppressing the events as far as I know, since the listener is a passive recorder.

You may be able to prevent the echoing to the prompt by reading from `stdin`; this will block, so you will have to do it in a separate thread. This will not block echoing to the terminal while the program is running however; perhaps [getpass](https://docs.python.org/3/library/getpass.html) would work?

**Comment by m27315** [comment]
Yes, I'm using Linux.

Thanks for the suggestions.  It sounds like what I want is beyond the scope of this module, so I'll close the issue.

Thanks for the prompt help and good luck! :smiley:
