### ISSUE TITLE
Use internal keyboard state in the win32 keyboard listener

### ISSUE THREAD

**Issue by moses-palmer** [moses-palmer/pynput#49]
# Rationale

Currently, *pynput* relies on the operating system keyboard state when translating scan codes to actual characters or keys. This has a number of advantages:
*  There is no need to maintain a keyboard state inside *pynput*
*  We can use [`ToUnicodeEx`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646322(v=vs.85).aspx) to translate key presses to actual unicode characters.

Unfortunately, it also brings a number of drawbacks:
*  `ToUnicodeEx` modifies a global keyboard buffer, leading to race conditions with other applications.
*  It requires applying some hacks, since the keyboard state is not fully updated when our system hook is called.
*  It is the main suspect for #15, #34 and #42

# Suggested solution

We should use the output of [MapVirtualKeyEx](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646307(v=vs.85).aspx) to update an internal keyboard state for each listener.

This will require some research into what the state actually should contain, and suitable methods to update it. The solution must be able to fully match the expected behaviour of a *pynput* keyboard listener, and respect the current keyboard layout.

**Comment by bschley** [comment]
How I exacly use the win32_event_filter?

with keyboard.Listener(on_press=on_press, on_release=None, kwargs=**<can`t get it to work>**) as listener:
...

**Comment by BA-24** [comment]
I have stumbled upon this issue myself, however, I don't think using the ``win32_event_filter`` is a real solution since it undermines a significant portion of the code written for it to be cross-compatible. The way this problem manifests on my PC is that all keyboard inputs are significantly delayed after switching from using the listener with the suppressed flag and then going back to using it without the suppressed flag (no matter any background tasks). I am fully willing to arrange some sort of setup using something like TeamViewer if you want to play around with the issue on a machine where you can easily reproduce it.

Here is the code I'm using to produce the bug

```py
from pynput.keyboard import Key, Listener

keyThread = None

def on_press(key):
    if key == Key.esc: keyThread.stop() # stop code
    
    elif key == Key.pause: # restart with suppress
        keyThread.stop()
        startListener(suppress=True)
        
    elif key == Key.backspace: # restart without suppress
        keyThread.stop()
        startListener()
        
    print(key) # print key


def startListener(suppress=False):
    global keyThread

    with Listener(on_press=on_press, suppress=suppress) as keyThread:
        keyThread.join()
        
startListener()
```
To reproduce it, you can run the code, open some sort of text editor and press the ``pause`` key followed by the ``backspace`` key and then try writing some text.
