### ISSUE TITLE
Access keyboard Unicode characters

### ISSUE THREAD

**Issue by masoudr** [moses-palmer/pynput#50]
Hi,
I want to detect Unicode characters from keyboard events. I tried the simple example of your code but the problem is if I change my input language from EN to another Unicode language like Spanish or Arabic it still shows the old characters and I need to rerun my script. I tried this simple code to detect Alt+Shift and reload the module to take effect but no luck.

```
import pynput
from importlib import reload

# The key combination to check
COMBINATION = {pynput.keyboard.Key.shift, pynput.keyboard.Key.alt_l}

# The currently active modifiers
current = set()

def on_press(key):
    print("current key is: ",key)
    if key in COMBINATION:
        current.add(key)
        if all(k in current for k in COMBINATION):
            print('All modifiers active!')
            listener.stop()

def on_release(key):
    try:
        current.remove(key)
    except KeyError:
        pass

with pynput.keyboard.Listener(on_press=on_press, on_release=on_release) as listener:
    listener.join()

print("Done")
reload(pynput)
import pynput as pynput2

def on_press2(key2):
    print("current key2 is: ",key2)


with pynput2.keyboard.Listener(on_press=on_press2) as listener:
    listener.join()
```
Thanks.

**Comment by moses-palmer** [comment]
Thank you for your report.

On what platform is this---Linux, macOS or Windows?

On 19 Sep 2017 6:47 am, "Masoud R." <notifications@github.com> wrote:

Hi,
I want to detect Unicode characters from keyboard events. I tried the
simple example of your code but the problem is if I change my input
language from EN to another Unicode language like Spanish or Arabic it
still shows the old characters and I need to rerun my script. I tried this
simple code to detect Alt+Shift and reload the module to take effect but no
luck.

import pynput
from importlib import reload

# The key combination to check
COMBINATION = {pynput.keyboard.Key.shift, pynput.keyboard.Key.alt_l}

# The currently active modifiers
current = set()

def on_press(key):
    print("current key is: ",key)
    if key in COMBINATION:
        current.add(key)
        if all(k in current for k in COMBINATION):
            print('All modifiers active!')
            listener.stop()

def on_release(key):
    try:
        current.remove(key)
    except KeyError:
        pass

with pynput.keyboard.Listener(on_press=on_press,
on_release=on_release) as listener:
    listener.join()

print("Done")
reload(pynput)
import pynput as pynput2

def on_press2(key2):
    print("current key2 is: ",key2)


with pynput2.keyboard.Listener(on_press=on_press2) as listener:
    listener.join()

Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/moses-palmer/pynput/issues/50>, or mute the thread

**Comment by masoudr** [comment]
Windows

**Comment by moses-palmer** [comment]
I have attempted to reproduce the error. My default keyboard layout is _Swedish_; for the purpose of troubleshooting, I installed _Arabic (Iraq)_.

I used the following simple test program:
```python
from pynput import keyboard

def on_press(key):
    if key == keyboard.Key.esc:
        listener.stop()
    else:
        print(ord(getattr(key, 'char', '0')))

controller = keyboard.Controller()
with keyboard.Listener(
        on_press=on_press) as listener:
    listener.join()
```

Starting the program with my default keyboard layout, I verified that the characters were registered correctly, and then I switched keyboard layouts. The new layout keys were registered as expected.

Please note that there is one caveat: *pynput* uses the keyboard layout of the current foreground thread, which is the owner of the active window. If this window belongs to `cmd.exe`, the layout reported does not correspond to the system layout for some reason. Can you please verify that the issue persists if you select another window?

**Comment by masoudr** [comment]
You are right about that.
I tried to write the output of the program to a text file, If I focus on cmd (console window) it can't detect the current language and always show the old one, but If change my focus window to another like desktop it works fine. Anyway, I don't want the console itself and I want to detect the keystrokes on any window.
Thanks.

**Comment by unistudyper** [comment]
hi can you advice more in this regard still no luck in detecting another language when changed

**Comment by masoudr** [comment]
@unistudyper If I remember correctly I had a problem with the latest version, try to use older versions and check out the above examples. It should work fine on Unicode chars.
