### ISSUE TITLE
MacOSX: Code not registering alphanumeric keys

### ISSUE THREAD

**Issue by haoflynet** [moses-palmer/pynput#57]
It's like the reference to #27 . But I'm not the same. After I run it as root, the alphanumeric keys is not registered, neither. I changed my `on_press` like this:
```python
def on_press(key):
    print(key.__dict__)
    print(key)
```
when i press the `a`, it print:
```
{'vk': 0, 'char': None, 'is_dead': False, 'combining': None}
<0>
```
and when i press the `cmd`, it print:
```
{'_value_': <55>, '_name_': 'cmd', '__objclass__': <enum 'Key'>}
Key.cmd
```
My System is macOS High Sierra(10.13.1), is there any way to fix it?

**Comment by moses-palmer** [comment]
I think that the numeric keypad may be unsupported on macOS. I will try to
allocate some time later today to look into it; I think the original reason
for not including it was that I could find key definitions in the headers.

On 2 Dec 2017 09:40, "haofly" <notifications@github.com> wrote:

It's like the reference to #27
<https://github.com/moses-palmer/pynput/issues/27> . But I'm not the same.
After I run it as root, the alphanumeric keys is not registered, neither. I
changed my on_press like this:

def on_press(key):
    print(key.__dict__)
    print(key)

when i press the a, it print:

{'vk': 0, 'char': None, 'is_dead': False, 'combining': None}
<0>

and when i press the cmd, it print:

{'_value_': <55>, '_name_': 'cmd', '__objclass__': <enum 'Key'>}
Key.cmd

My System is macOS High Sierra(10.13.1), is there any way to fix it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/moses-palmer/pynput/issues/57>, or mute the thread

**Comment by haoflynet** [comment]
Maybe, I found the original code which may cause the fault:
In `pynput/_util/darwin.py`:
```
layout = _wrap_value(CarbonExtra.TISGetInputSourceProperty(keyboard, CarbonExtra.kTISPropertyUnicodeKeyLayoutData))
```
In my case, the `keyboard` is `4572894496`, the `CarbonExtra.kTISPropertyUnicodeKeyLayoutData` is `c_void_p(4494860328)`, but the `layout` is None.

**Comment by moses-palmer** [comment]
Could you add logging of in-parameters to _wrap_value[](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/_util/darwin.py#L44)? This function is somewhat of a hack to acquire access to _PyOBJ_ internals.

**Comment by haoflynet** [comment]
The `CarbonExtra.TISGetInputSourceProperty(keyboard, CarbonExtra.kTISPropertyUnicodeKeyLayoutData)` is None, so the `_wrap_value` can not working.

**Comment by haoflynet** [comment]
My keyboard layout is `Chinese`, according to the https://lists.apple.com/archives/cocoa-dev/2009/Aug/msg01510.html, I change my keyboard layout to `American`, then it worked.  😃

**Comment by haoflynet** [comment]
For non-unicode layouts, such as Chinese or Japanese, this may be one solution: https://github.com/davedelong/DDHotKey/commit/d5e6ab5bad050d21d93781a5e4e8c6e60ca449e6

**Comment by moses-palmer** [comment]
Thank you for the research! Perhaps you could test the solution detailed in the link above? The ovious place for the change would be in [keyboard_context](https://github.com/moses-palmer/pynput/blob/master/lib/pynput/_util/darwin.py#L119). I would very much appreciate a pull request!

**Comment by haoflynet** [comment]
I'd love to do!

**Comment by moses-palmer** [comment]
I have merged your pull request. Thank you very much!
