### ISSUE TITLE
name 'keyboard' is not defined

### ISSUE THREAD

**Issue by andreguiw** [moses-palmer/pynput#599]
I got this nameError exactly where all events are being called using the non blocking fashion in my last function of the code which I defined as start() as you guys can see in the print below. Is anyone having this issue??

![nameerror](https://github.com/moses-palmer/pynput/assets/158860000/c67eb380-e829-4109-b6b0-d1564596a47c)

**Comment by moses-palmer** [comment]
Thank you for your report.

Since you only have included a screenshot and not the full source, I can only make a guess as to what the issue might be, but the Python interpreter raising a `NameError` indicates that you have not imported the keyboard module. Are you sure that you have an `from pynput import keyboard` statement at the top of the file?

I will close this issue, as I doubt that this is a bug with _pynput_. If you disagree, please reopen.
