### ISSUE TITLE
Bad display name ""   when running via ssh

### ISSUE THREAD

**Issue by wroscoe** [moses-palmer/pynput#6]
Hi,

I'm trying to use this package to control a Raspberry Pi to drive an RC car from my laptop via wifi. Is it possible to use this package to capture key strokes from my laptop while running the script on the Pi via ssh?
 The script with pynput works great when I run directly from the Pi. 

Thanks

```
Traceback (most recent call last):
  File "keycontrol.py", line 28, in <module>
    from pynput.keyboard import Key, Listener, KeyCode
  File "/home/pi/code/donkey/env/lib/python3.4/site-packages/pynput/__init__.py", line 23, in <module>
    from . import keyboard
  File "/home/pi/code/donkey/env/lib/python3.4/site-packages/pynput/keyboard/__init__.py", line 49, in <module>
    from ._xorg import KeyCode, Key, Controller, Listener
  File "/home/pi/code/donkey/env/lib/python3.4/site-packages/pynput/keyboard/_xorg.py", line 38, in <module>
    from pynput._util.xorg import (
  File "/home/pi/code/donkey/env/lib/python3.4/site-packages/pynput/_util/xorg.py", line 38, in <module>
    _check()
  File "/home/pi/code/donkey/env/lib/python3.4/site-packages/pynput/_util/xorg.py", line 36, in _check
    display = Xlib.display.Display()
  File "/home/pi/code/donkey/env/lib/python3.4/site-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/home/pi/code/donkey/env/lib/python3.4/site-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/home/pi/code/donkey/env/lib/python3.4/site-packages/Xlib/protocol/display.py", line 53, in __init__
    name, host, displayno, screenno = connect.get_display(display)
  File "/home/pi/code/donkey/env/lib/python3.4/site-packages/Xlib/support/connect.py", line 62, in get_display
    return mod.get_display(display)
  File "/home/pi/code/donkey/env/lib/python3.4/site-packages/Xlib/support/unix_connect.py", line 47, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
```

**Comment by moses-palmer** [comment]
On Linux, *pynput* uses *X* to control the keyboard.

When creating an *X* connection, the target display/session is specified with the `$DISPLAY` environment variable. When you run your script directly from the Pi, it will be set correctly since the terminal was launched from an X session, but when connecting through *SSH* it will not.

Get the value of `$DISPLAY` when you run the script locally on the Pi, and set it when running the script remotely:
```
$ ssh pi.local
$ DISPLAY=":0" python my-script.py
```

If you intend to pass keystrokes from your laptop to the Pi, please note the following:
*  **You will only be able to control an *X* session; you cannot emulate actual hardware presses.** If you intent to control an application running in an *X* session, this is not a problem.
*  **Configuring *X* does not appear to be trivial.** You will need to connect remotely to *X*.

A simple, untested, script to pass keystrokes is:
```python
import os
from pynput import keyboard

def on_press(key):
    controller.press(key)

def on_release(key):
    controller.release(key)

with keyboard.Listener(
        on_press=on_press,
        on_release=on_release) as listener:
    # Specify a different target display
    os.environ['DISPLAY'] = os.environ['REMOTE_DISPLAY']
    controller = keyboard.Controller()
    listener.join()
```

**Comment by moses-palmer** [comment]
If you decide to try, you may want to use [this branch](https://github.com/moses-palmer/pynput/tree/fixup-xlib-multiple-displays). The master branch will cause infinite feedback in the event loop.

**Comment by raseribanez** [comment]
Hi, I am having the same issue. So I have created a remote SSH connection via putty to my Raspberry Pi. I can do this from both my Linux and Windows systems. I have a very simple Keylog script written in Python, and it runs smoothly, it saves keystrokes into a log file. I can't deploy this through the SSH connection though. The above example differs to mine because I want to save the output in a separate file.

Currently, when I run the script from the SSH environment, I get the same bad-display error. I thought the problem was to do with there being 2 keyboards to potentially log (both ends of the SSH connection) and this was causing problems. But I am still learning.

Is there a way to run this script on my Pi (Raspbian) from the SSH environment (Putty) and save my output into a log or text file?

 BTW This is all above board, the raspberry Pi and computers are my own and I connect using my own username and password etc. I am studying computing and IT in Uni - first year, and just messing around with an activity we are doing.

**Comment by yzy1996** [comment]
> On Linux, _pynput_ uses _X_ to control the keyboard.
> 
> When creating an _X_ connection, the target display/session is specified with the `$DISPLAY` environment variable. When you run your script directly from the Pi, it will be set correctly since the terminal was launched from an X session, but when connecting through _SSH_ it will not.
> 
> Get the value of `$DISPLAY` when you run the script locally on the Pi, and set it when running the script remotely:
> 
> ```
> $ ssh pi.local
> $ DISPLAY=":0" python my-script.py
> ```
> If you intend to pass keystrokes from your laptop to the Pi, please note the following:
> 
> * **You will only be able to control an _X_ session; you cannot emulate actual hardware presses.** If you intent to control an application running in an _X_ session, this is not a problem.
> * **Configuring _X_ does not appear to be trivial.** You will need to connect remotely to _X_.
> 
> A simple, untested, script to pass keystrokes is:
> 
> ```python
> import os
> import queue
> from pynput import keyboard
> 
> q = queue.Queue()
> with keyboard.Listener(
>         on_press=lambda k: q.put_nowait((k, True)),
>         on_release=lambda k: q.put_nowait((k, False))) as listener:
>     os.environ['DISPLAY'] = os.environ['REMOTE_DISPLAY']
>     controller = keyboard.Controller()
>     while True:
>         controller.touch(*q.get())
> ```

Th

> On Linux, _pynput_ uses _X_ to control the keyboard.
> 
> When creating an _X_ connection, the target display/session is specified with the `$DISPLAY` environment variable. When you run your script directly from the Pi, it will be set correctly since the terminal was launched from an X session, but when connecting through _SSH_ it will not.
> 
> Get the value of `$DISPLAY` when you run the script locally on the Pi, and set it when running the script remotely:
> 
> ```
> $ ssh pi.local
> $ DISPLAY=":0" python my-script.py
> ```
> If you intend to pass keystrokes from your laptop to the Pi, please note the following:
> 
> * **You will only be able to control an _X_ session; you cannot emulate actual hardware presses.** If you intent to control an application running in an _X_ session, this is not a problem.
> * **Configuring _X_ does not appear to be trivial.** You will need to connect remotely to _X_.
> 
> A simple, untested, script to pass keystrokes is:
> 
> ```python
> import os
> import queue
> from pynput import keyboard
> 
> q = queue.Queue()
> with keyboard.Listener(
>         on_press=lambda k: q.put_nowait((k, True)),
>         on_release=lambda k: q.put_nowait((k, False))) as listener:
>     os.environ['DISPLAY'] = os.environ['REMOTE_DISPLAY']
>     controller = keyboard.Controller()
>     while True:
>         controller.touch(*q.get())
> ```

Thanks! This solved my problem!

**Comment by spidy1996** [comment]
it says Key Error: 'REMOTE_DISPLAY'

**Comment by jangid** [comment]
What if my linux-box doesn't have X installed? I have a debian machine without GUI. And I have encountered the same issue 'Bad display name ""'.

**Comment by moses-palmer** [comment]
In that case, *pynput* will not work; it is an *X* client. See #184 for a possible future solution.

**Comment by Remi-EA** [comment]
Hi,

After running via ssh on an embedded computer (on linux) my code who uses pynput package I get the error
 `Xlib.error.DisplayNameError: Bad display name ""` 
So I tried `$ DISPLAY=":0" python my-script.py` because I checked locally `echo $DISPLAY` and got : `:0` 
But then I got this error : `Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified\n'` 

I want to use pynput's keypress detection on the embedded computer who only has a keyboard connected, while running the script on my laptop via ssh, is it possible ?

Thanks

**Comment by kasrakazemi** [comment]
> @spidy1996 @Remi-EA @raseribanez @jangid @wroscoe After trying to find solution, I decided to write a simple library around this spesific issue: [sshkeyboard](https://sshkeyboard.readthedocs.io/en/latest/)
> 
> It allows you to react to user input even through SSH, and it is perfect for example for driving a RC car on Raspberry Pi.
> 
> It is many other ways inferior solution to pynput, but it does this one and only thing pretty well.

Hi @ollipal 
i tried to run 
`from sshkeyboard import listen_keyboard

def press(key):
    print(f"'{key}' pressed")

def release(key):
    print(f"'{key}' released")

listen_keyboard(
    on_press=press,
    on_release=release,
)
`
but continually face with this error:
`RuntimeError: asyncio.run() cannot be called from a running event loop`
is there any solution for this?

**Comment by ollipal** [comment]
(@kasrakazemi I replied [here](https://github.com/ollipal/sshkeyboard/issues/2#issuecomment-1033383716))
