### ISSUE TITLE
keyboard.Listener class - Supress events for Linux/Xorg?

### ISSUE THREAD

**Issue by TheoRet** [moses-palmer/pynput#68]
Hello,
I am using Linux Mint 18 and I am looking for a keyhook that can capture key events and supress them system-wide.

According to the documentation, the keyboard.Listener class supports this using kw-arguments on windows and mac. Is there any way to achieve this using xorg?

Thanks for the nice documentation btw!

**Comment by karamjaber** [comment]
@TheoRet  where did you see in the documentation that it is possible to suppress keys on windows?

**Comment by moses-palmer** [comment]
Hello,

This is unfortunately not possible currently.

Completely consuming events is possible on _Xorg_ using [Xlib.display.Window.grab_keyboard](http://python-xlib.sourceforge.net/doc/html/python-xlib_21.html). Since this request has come up twice in just a couple of days, I will add it to the roadmap.

**Comment by moses-palmer** [comment]
See
http://pynput.readthedocs.io/en/latest/keyboard.html#pynput.keyboard.Listener
.

It is documented under keyword arguments.

**Comment by gliviu** [comment]
I would like to extend this request to mouse events also. I'm trying to intercept thumb buttons and implement some system wide scrolling mechanism. Unfortunately chrome browser has them assigned as back/forward actions. Suppressing events only for those two buttons would help solve this situation.

**Comment by moses-palmer** [comment]
My feature branch adds the argument `suppress` to all listener types. When
I have tested it on all platforms, I will merge it into master.

On 6 Feb 2018 09:18, "Liviu Grigorescu" <notifications@github.com> wrote:

I would like to extend this request to mouse events also. I'm trying to
intercept thumb buttons and implement some system wide scrolling mechanism.
Unfortunately chrome browser has them assigned as back/forward actions.
Suppressing events only for those two buttons would help solve this
situation.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/moses-palmer/pynput/issues/68#issuecomment-363344705>,
or mute the thread

**Comment by moses-palmer** [comment]
I have merged the feature branch to master, but I will add a few more features before making a release.

**Comment by gliviu** [comment]
I'll give it a try on windows/linux in the following days.

**Comment by gliviu** [comment]
What about suppressing selective keys. Let's say I want suppress all buttons except left. See code below. Would it be possible?

```python
def on_click(x, y, button, pressed):
    if button==mouse.Button.left
        # pass event through
    else
       print(button)  # button suppressed
with mouse.Listener(on_click=on_click, suppress=True) as listener:
    listener.join()
```

**Comment by moses-palmer** [comment]
That is unfortunately not possible on _Xorg_; there it's either all or nothing.

**Comment by TheoRet** [comment]
Wow, this is great support! Thanks moses-palmer for the quick 
implementation. I will try it when I find the time.

I was thinking about using PyUserInput for this, but it turned out to be 
quite buggy and does not have such a good documentation. so I think I 
will switch to pynput.

@gliviu:

if you want a workaround for selective key suppressing, you could try 
using xbindkeys. It supresses the bound keys by default. You just need 
to find a method of  turning it on and off from python.

**Comment by gliviu** [comment]
Well, this is how I ended up using PyUserInput and now pynput -[map-mouse-button-to-scrolling-behaviour](https://askubuntu.com/questions/993712/map-mouse-button-to-scrolling-behaviour/1000685#1000685)

Unfortunately the xbindkeys solution does not work if I want to transform thumb button presses in mouse wheel movement due to some bug combination between [xlib/xbindkeys/xte...](https://askubuntu.com/questions/455762/xbindkeys-wont-work-properly).
The workaround I proposed in that answer was to use keyboard up/down instead of mouse wheel which works but is not the perfect solution (ie in a text editor it moves the cursor instead of scrolling).

No time frame but I hope I'll figure this out using just pynput.

**Comment by TheoRet** [comment]
maybe this can be of help?

https://github.com/philipl/evdevremapkeys

**Comment by gliviu** [comment]
Thanks, I'll give it a try.

**Comment by jayquonmarton** [comment]
@moses-palmer 
> This is unfortunately not possible currently.
> 
> Completely consuming events is possible on _Xorg_ using [Xlib.display.Window.grab_keyboard](http://python-xlib.sourceforge.net/doc/html/python-xlib_21.html).

That link also has Xlib.display.Window.grab_key. Does that api not provide a way to implement the requested selective-suppression feature? Perhaps you could take as input a set of keys to be selectively suppressed and use those along with the grab_key api?
